-- CREACION DE BASE DE DATOS
CREATE SCHEMA IF NOT EXISTS AGENCIA_VIAJES;

USE AGENCIA_VIAJES;
-- CREACION DE TABLA LISTADO_AGENCIA
DROP TABLE IF EXISTS LISTADO_AGENCIA;
CREATE TABLE IF NOT EXISTS LISTADO_AGENCIA (
    ID_RES          INT,
    VENTA           DECIMAL(15,2),
    COSTO           DECIMAL(15,2),
    VENTAUS         DECIMAL(15,2),
    COSTOUS         DECIMAL(15,2),
    CIE_OPE         INT,
    CIE_RES         INT,
    CIE_CLI         INT,
    CIE_FAC         INT,
    COMIS           DECIMAL(15,2),
    COBROS          DECIMAL(15,2),
    COBROSUS        DECIMAL(15,2),
    PAGOS           DECIMAL(15,2),
    PAGOSUS         DECIMAL(15,2),
    FEC_APE         DATETIME,
    FEC_SAL         DATETIME,
    FEC_COM         DATETIME,
    NOM_USU         VARCHAR(100),
    NOM_CLI         VARCHAR(150),
    NOMBRE          VARCHAR(150),
    ADEL            DECIMAL(15,2),
    NOM_OPE         VARCHAR(100),
    FACTURADO       DECIMAL(15,2),
    FACTURADOUS     DECIMAL(15,2),
    ID_CLI          INT,
    GASTOS          DECIMAL(15,2),
    GASTOSUS        DECIMAL(15,2),
    SER_COT         INT,
    FECHA_TICKET    VARCHAR(20),
    FECHA_VTO       VARCHAR(20),
    ID_USU_CIERRE   VARCHAR(20),
    ID_USU_APERTURA VARCHAR(20),
    FECHA_CIERRE    DATETIME,
    NUM_PAX         INT,
    DETALLE_VIAJE   VARCHAR(255),
    LIQUIS          DECIMAL(15,2),
    FECLIQ          DECIMAL(15,2),
    PROMOTOR        VARCHAR(100),
    FACTURAS        VARCHAR(500),
    RECIBOS         VARCHAR(1000),
    VEND2           VARCHAR(100),
    DEPTO           VARCHAR(100),
    OPERATIVO       VARCHAR(100),
    ID_CLI2         INT
);

-- CREACION DE TABLA CON COLUMNAS A UTILIZAR
DROP TABLE IF EXISTS listado_agencia_resumido;
CREATE TABLE listado_agencia_resumido AS
SELECT 
    ID_RES,
    NOM_CLI,
    VENTAUS,
    COBROSUS,
    COSTOUS,
    PAGOSUS,
    GASTOSUS,
    FEC_SAL,
    NUM_PAX,
    DETALLE_VIAJE,
    NOM_USU,
    DEPTO
FROM listado_agencia;

SELECT * FROM listado_agencia_resumido;

-- Exploracion de tabla
SELECT COUNT(*) AS total_registros
FROM listado_agencia_resumido;

-- RESUMEN ANUAL DE KPIs FINANCIEROS
SELECT
    COUNT(ID_RES)                                                        AS TOTAL_RESERVAS,
    ROUND(SUM(VENTAUS), 2)                                               AS VENTAUS_TOTAL,
    ROUND(SUM(COSTOUS), 2)                                               AS COSTOUS_TOTAL,
    ROUND(AVG(VENTAUS), 2)                                               AS VENTAUS_PROMEDIO,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)                          AS MARGEN_TOTAL,
    ROUND(
        SUM(VENTAUS - COSTOUS - GASTOSUS) / NULLIF(SUM(VENTAUS), 0) * 100
    , 2)                                                                 AS MARGEN_PCT,
    COUNT(CASE WHEN (VENTAUS - COBROSUS) > 0 THEN 1 END)                AS RESERVAS_NOCOBRADAS,
    ROUND(
        COUNT(CASE WHEN (VENTAUS - COBROSUS) > 0 THEN 1 END) / COUNT(ID_RES) * 100
    , 2)                                                                 AS RESERVAS_NOCOBRADAS_PCT,
    ROUND(SUM(CASE WHEN (VENTAUS - COBROSUS) > 0 THEN (VENTAUS - COBROSUS) ELSE 0 END), 2)
                                                                         AS MONTO_NOCOBRADO_TOTAL
FROM listado_agencia_resumido;

-- -- ANÁLISIS MENSUAL DE RESERVAS Y KPIs FINANCIEROS
SELECT
    YEAR(FEC_SAL)                                   AS ANIO,
    MONTH(FEC_SAL)                                  AS MES_NUM,
    DATE_FORMAT(FEC_SAL, '%Y-%m')                   AS MES,
    COUNT(ID_RES)                                   AS TOTAL_RESERVAS,
    ROUND(AVG(COUNT(ID_RES)) OVER (), 2)            AS PROMEDIO_RESERVAS_MES,
    ROUND(SUM(VENTAUS), 2)                          AS VENTAUS_TOTAL,
    ROUND(SUM(COSTOUS), 2)                          AS COSTOUS_TOTAL,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)     AS MARGEN_TOTAL,
    ROUND(
        SUM(VENTAUS - COSTOUS - GASTOSUS) / NULLIF(SUM(VENTAUS), 0) * 100
    , 2)                                            AS MARGEN_PCT
 FROM listado_agencia_resumido
WHERE FEC_SAL IS NOT NULL
GROUP BY ANIO, MES_NUM, MES
ORDER BY ANIO, MES_NUM;

-- CLASIFICACIÓN DE DESTINOS Y VENTAS POR REGION
SELECT
    CASE
        WHEN DETALLE_VIAJE REGEXP 'BRASIL|BUZIOS|BÚZIOS|RIO|ANGRA|ARRAIAL|NATAL|PIPA|MACEIO|MACEIÓ|MARAGOGI|PORTO DE GALINHAS|PORTO GALINHAS|FLORIANOPOLIS|CAMBORIU|PRAIA DO FORTE|PORTO SEGURO|SALVADOR|TRANCOSO|IMBASSAI|BARRA DA TIJUCA|BARRA DE TIJUCA|SAUIPE|FORTALEZA|ILHABELA|BOMBINHAS|CANASVIEIRAS|BEACH PARK|CLUB MED|JERICOACOARA|SSA|FLN|BRC|COSTAO|RECIFE|BELEM|BOIPABA|CABO FRIO|SAO PAULO|NORDESTE|NORTE BRASIL|NORTE DE BRASIL' THEN 'BRASIL'
        WHEN DETALLE_VIAJE REGEXP 'PUNTA CANA|PUJ|BAYAHIBE|MICHES|SAMANA|SAMANÁ|DOMINICANA|REP DOM|CARIBE|CAYO LARGO|CUBA|VARADERO|JAMAICA|NEGRIL|MONTEGO|SAN JUAN|PUERTO PLATA|LAS TERRENAS|COSTA MUJERES|PLAYA MUJERES|BAVARO' THEN 'CARIBE'
        WHEN DETALLE_VIAJE REGEXP 'EUROPA|ITALIA|ROMA|FLORENCIA|SICILIA|CERDEÑA|BARI|NAPOLES|SORRENTO|AMALFI|PUGLIA|CAMPANIA|ESPAÑA|MADRID|BARCELONA|SEVILLA|VALENCIA|GRANADA|ANDALUCIA|PORTUGAL|OPORTO|PARIS|FRANCIA|LONDON|LONDRES|INGLATERRA|ESCOCIA|IRLANDA|AMSTERDAM|BRUSELAS|BRUJAS|LUXEMBURGO|ALEMANIA|SUIZA|FRANKFURT|ALSACIA|NORUEGA|OSLO|BERGEN|COPENHAGUE|GRECIA|TURQUIA|TURQUÍA|MARRUECOS|EUROPAMUNDO|VERDE SICI|ALMA EUROPEA|PANORAMA EUROPEO' THEN 'EUROPA'
        WHEN DETALLE_VIAJE REGEXP 'EEUU|ESTADOS UNIDOS|USA|MIAMI|ORLANDO|NEW YORK|NUEVA YORK|NYC|FLORIDA|WASHINGTON|CHICAGO|DISNEY|UNIVERSAL|COSTA OESTE|CANADA' THEN 'EEUU / NORTEAMÉRICA'
        WHEN DETALLE_VIAJE REGEXP 'MEXICO|MÉXICO|CANCUN|CANCÚN|PLAYA DEL CARMEN|PLAYACAR|RIVIERA MAYA|TULUM|COSTA RICA|PANAMA|PANAMÁ|GUATEMALA|COZUMEL|PLAYA BLANCA|SAN JOSE' THEN 'MÉXICO / CENTROAMÉRICA'
        WHEN DETALLE_VIAJE REGEXP 'PERU|PERÚ|LIMA|CUSCO|CUZCO|MACHU PICCHU|COLOMBIA|CARTAGENA|BOGOTA|BARU|CHILE|SANTIAGO|BARILOCHE|PUERTO VARAS|PUCON|ATACAMA|IGUAZU|IGUAZÚ|FOZ|ARUBA|CURAZAO|CURACAO|URUGUAY|MONTEVIDEO|PARAGUAY|ASUNCION|SAN ANDRES|GALAPAGOS' THEN 'SUDAMÉRICA / CARIBE SUR'
        WHEN DETALLE_VIAJE REGEXP 'CHINA|JAPON|JAPÓN|DUBAI|DOHA|INDIA|EGIPTO|JORDANIA|ISRAEL|MALDIVAS|COREA|HONG KONG|AUSTRALIA|SAFARI|AONANG' THEN 'ASIA / MEDIO ORIENTE'
        WHEN DETALLE_VIAJE REGEXP 'CRUCERO|MSC|COSTA CRUCEROS|COSTA DIADEMA|TRANSATLANTICO|TRASATLANTICO' THEN 'CRUCEROS'
        ELSE 'SIN CLASIFICAR'
    END                                                             AS REGION,
    COUNT(ID_RES)                                                   AS TOTAL_RESERVAS,
    ROUND(SUM(VENTAUS), 2)                                          AS VENTAUS_TOTAL,
    ROUND(SUM(VENTAUS) / NULLIF((SELECT SUM(VENTAUS) FROM listado_agencia_resumido), 0) * 100, 2) AS VENTAUS_PCT,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)                     AS MARGEN_TOTAL,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS) / NULLIF(SUM(VENTAUS), 0) * 100, 2) AS MARGEN_PCT
FROM listado_agencia_resumido
WHERE DETALLE_VIAJE IS NOT NULL
GROUP BY REGION
ORDER BY VENTAUS_TOTAL DESC;

-- MARGEN Y VENTAS POR DEPARTAMENTO / SUCURSAL
SELECT
    CASE 
        WHEN DEPTO IS NULL OR DEPTO = '' THEN 'SIN ASIGNAR'
        ELSE DEPTO 
    END                                                                  AS DEPARTAMENTO,
    COUNT(ID_RES)                                                        AS TOTAL_RESERVAS,
    ROUND(SUM(VENTAUS), 2)                                               AS VENTAUS_TOTAL,
    ROUND(
        SUM(VENTAUS) / NULLIF((SELECT SUM(VENTAUS) FROM listado_agencia_resumido), 0) * 100
    , 2)                                                                 AS VENTAUS_PCT,
    ROUND(SUM(COSTOUS), 2)                                               AS COSTOUS_TOTAL,
    ROUND(SUM(GASTOSUS), 2)                                              AS GASTOSUS_TOTAL,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)                          AS MARGEN_TOTAL,
    ROUND(
        SUM(VENTAUS - COSTOUS - GASTOSUS) / NULLIF(SUM(VENTAUS), 0) * 100
    , 2)                                                                 AS MARGEN_PCT
FROM listado_agencia_resumido
GROUP BY DEPARTAMENTO
ORDER BY VENTAUS_TOTAL DESC;

-- CTE: RANKING DE VENDEDORES CON CATEGORÍA DE PERFORMANCE
WITH ventas_por_vendedor AS (
    SELECT
        NOM_USU                                             AS VENDEDOR,
        COUNT(ID_RES)                                       AS TOTAL_RESERVAS,
        ROUND(SUM(VENTAUS), 2)                              AS VENTAUS_TOTAL,
        ROUND(AVG(VENTAUS), 2)                              AS TICKET_PROMEDIO,
        ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)         AS MARGEN_TOTAL,
        ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS) 
            / NULLIF(SUM(VENTAUS), 0) * 100, 2)             AS MARGEN_PCT
    FROM listado_agencia_resumido
    WHERE NOM_USU IS NOT NULL
    GROUP BY NOM_USU
)
SELECT
    VENDEDOR,
    TOTAL_RESERVAS,
    VENTAUS_TOTAL,
    TICKET_PROMEDIO,
    MARGEN_TOTAL,
    MARGEN_PCT,
    RANK() OVER (ORDER BY VENTAUS_TOTAL DESC)               AS RANKING,
    CASE
        WHEN VENTAUS_TOTAL >= (SELECT AVG(VENTAUS_TOTAL) * 1.2 FROM ventas_por_vendedor) THEN 'ALTO RENDIMIENTO'
        WHEN VENTAUS_TOTAL >= (SELECT AVG(VENTAUS_TOTAL) FROM ventas_por_vendedor)       THEN 'RENDIMIENTO MEDIO'
        ELSE 'BAJO RENDIMIENTO'
    END                                                     AS CATEGORIA
FROM ventas_por_vendedor
ORDER BY RANKING;

-- WINDOW FUNCTIONS: EVOLUCIÓN MENSUAL CON ACUMULADO Y VARIACIÓN
SELECT
    DATE_FORMAT(FEC_SAL, '%Y-%m')                           AS MES,
    COUNT(ID_RES)                                           AS RESERVAS_MES,
    ROUND(SUM(VENTAUS), 2)                                  AS VENTAUS_MES,
    ROUND(SUM(VENTAUS - COSTOUS - GASTOSUS), 2)             AS MARGEN_MES,
    ROUND(SUM(SUM(VENTAUS)) 
        OVER (ORDER BY DATE_FORMAT(FEC_SAL, '%Y-%m')), 2)   AS VENTAUS_ACUMULADO,
    ROUND(SUM(VENTAUS) - LAG(SUM(VENTAUS)) 
        OVER (ORDER BY DATE_FORMAT(FEC_SAL, '%Y-%m')), 2)   AS VARIACION_VS_MES_ANT,
    ROUND(
        (SUM(VENTAUS) - LAG(SUM(VENTAUS)) 
            OVER (ORDER BY DATE_FORMAT(FEC_SAL, '%Y-%m')))
        / NULLIF(LAG(SUM(VENTAUS)) 
            OVER (ORDER BY DATE_FORMAT(FEC_SAL, '%Y-%m')), 0) * 100
    , 2)                                                    AS VARIACION_PCT
FROM listado_agencia_resumido
WHERE FEC_SAL IS NOT NULL
GROUP BY MES
ORDER BY MES;

